// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

/** Só para `prisma generate` em CI/Docker (sem env no build). Nunca conecta ao banco. */
const DATABASE_URL_FOR_CONFIG =
  process.env.DATABASE_URL ??
  'postgresql://build:build@127.0.0.1:5432/build?schema=public';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    /** `npx prisma db seed` — logs aparecem no terminal. */
    seed: 'ts-node --transpile-only prisma/seed.ts',
  },
  engine: 'classic',
  datasource: {
    url: DATABASE_URL_FOR_CONFIG,
  },
});
